@startuml "Registry Diagram"

struct ReporterRegistryImpl{
    Vector[] listeners
    Map[] factories
}


interface EventListenerFactory{
    create()
    getName()
    getDescription()
}

interface IReporterFactory{
    create(config)
    getDescription()
}


interface IRegistryHub {
    getReporterRegistry()
    getTestCaseRegsitry()
    getTagAliasRegistry()
}

interface IMutableRegistryHub{
    registerReporter()
    registerListener()
    registerTest()
    registerTranslator()
    registerTagAlias()
}

interface ITestCaseRegistry{
    getAllInfos()
    getAllTests()
    getAllTestsSorted()
}

interface ITestInvoker {
    +invoke()
}

class TestCasehanlde{
    - m_invoker
    - m_info
    + invoke()
    + getTestCaseInfo()
}

struct TestCaseInfo{
    - backingTags
    - internalAppendTag()
    + tag
    + lineInfo
    + properties
    + name
    + className
    + isHiden()
    + okToFail()
    + expectedToFail()
    + addFilenameTag()
    + tagAsString()
}

class ReporterFactory implements IReporterFactory
TestCasehanlde::m_invoker -l-o ITestInvoker
TestCasehanlde::m_info --o TestCaseInfo

class TestRegistry{
    + registerTest()
    - m_viewed_test_infos
    - Object[] m_invokers
    - Object[] m_handles
    - Object[] m_owned_test_infos
    - m_currentSortOrder
    - m_sortedFunctions
}

class TestRegistry implements ITestCaseRegistry


TestRegistry::m_invokers -u-> ITestInvoker

TestRegistry::m_owned_test_infos -u-*TestCaseInfo
TestRegistry::m_handles -r-> TestCasehanlde




class ReporterRegistry{
    + m_impl
    + create()
    + registerReporter()
    + registerListener()
    + getFactories()
    + getListeners()
}



ReporterRegistry::m_impl -u-> ReporterRegistryImpl
ReporterRegistryImpl::factories -u-> ReporterFactory
ReporterRegistryImpl::listeners -u-> EventListenerFactory



class RegistryHub {
    - m_testCaseRegistry
    - m_reporterRegistry
    - m_exceptionTrans
    - m_tagAl
}

class RegistryHub implements IRegistryHub
class RegistryHub implements IMutableRegistryHub
RegistryHub::m_reporterRegistry -u-> ReporterRegistry
RegistryHub::m_testCaseRegistry -u-> TestRegistry

@enduml
